import { Patient, Doctor, Report, Invoice, LabSettings, User } from '@/types';

const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const twoDaysAgo = new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0];

export const defaultLabSettings: LabSettings = {
  labName: 'LifeCare Diagnostics & Pathology Lab',
  address: '123, MG Road, Near City Hospital, Mumbai - 400001',
  phone: '+91 22 2345 6789',
  email: 'info@lifecarediagnostics.in',
  website: 'www.lifecarediagnostics.in',
  registrationNumber: 'MH/LAB/2024/12345',
  nablNumber: 'MC-12345',
  footerNote: 'This report is generated by computer and does not require a signature. Results should be correlated clinically.',
  pathologistName: 'Dr. Priya Sharma',
  qualification: 'MD (Pathology), DMLT',
};

export const defaultUsers: User[] = [
  { id: 'user-001', email: 'admin@lifecare.in', name: 'Admin User', role: 'admin', createdAt: '2024-01-01' },
  { id: 'user-002', email: 'staff@lifecare.in', name: 'Lab Technician', role: 'staff', createdAt: '2024-01-01' },
  { id: 'user-003', email: 'doctor@lifecare.in', name: 'Dr. Viewer', role: 'doctor', createdAt: '2024-01-01' },
];

export const sampleDoctors: Doctor[] = [
  { id: 'doc-001', name: 'Dr. Rajesh Gupta', specialization: 'General Physician', clinicName: 'City Health Clinic', mobile: '9876543210', referralCode: 'RG001', email: 'rajesh@clinic.in' },
  { id: 'doc-002', name: 'Dr. Sunita Patel', specialization: 'Gynecologist', clinicName: 'Women Care Hospital', mobile: '9876543211', referralCode: 'SP002', email: 'sunita@womencare.in' },
  { id: 'doc-003', name: 'Dr. Amit Verma', specialization: 'Cardiologist', clinicName: 'Heart Care Center', mobile: '9876543212', referralCode: 'AV003' },
  { id: 'doc-004', name: 'Dr. Neha Singh', specialization: 'Orthopedic', clinicName: 'Bone & Joint Clinic', mobile: '9876543213', referralCode: 'NS004' },
  { id: 'doc-005', name: 'Dr. Vikram Joshi', specialization: 'Pediatrician', clinicName: 'Child Care Hospital', mobile: '9876543214', referralCode: 'VJ005' },
];

export const samplePatients: Patient[] = [
  { id: 'pat-001', patientId: 'P-20240001', uhid: 'LC-001', name: 'Rahul Kumar', age: 35, gender: 'Male', mobile: '9988776601', city: 'Mumbai', referredBy: 'doc-001', registrationDate: twoDaysAgo, address: '45, Andheri West' },
  { id: 'pat-002', patientId: 'P-20240002', uhid: 'LC-002', name: 'Priya Sharma', age: 28, gender: 'Female', mobile: '9988776602', city: 'Mumbai', referredBy: 'doc-002', registrationDate: twoDaysAgo, address: '12, Bandra East' },
  { id: 'pat-003', patientId: 'P-20240003', uhid: 'LC-003', name: 'Vijay Mehta', age: 55, gender: 'Male', mobile: '9988776603', city: 'Pune', referredBy: 'doc-003', registrationDate: yesterday },
  { id: 'pat-004', patientId: 'P-20240004', uhid: 'LC-004', name: 'Anjali Desai', age: 42, gender: 'Female', mobile: '9988776604', city: 'Mumbai', referredBy: 'doc-001', registrationDate: yesterday },
  { id: 'pat-005', patientId: 'P-20240005', uhid: 'LC-005', name: 'Suresh Reddy', age: 60, gender: 'Male', mobile: '9988776605', city: 'Thane', referredBy: 'doc-003', registrationDate: today },
  { id: 'pat-006', patientId: 'P-20240006', uhid: 'LC-006', name: 'Meera Iyer', age: 32, gender: 'Female', mobile: '9988776606', city: 'Mumbai', referredBy: 'doc-002', registrationDate: today },
  { id: 'pat-007', patientId: 'P-20240007', uhid: 'LC-007', name: 'Deepak Jain', age: 48, gender: 'Male', mobile: '9988776607', city: 'Mumbai', referredBy: 'doc-004', registrationDate: today },
  { id: 'pat-008', patientId: 'P-20240008', uhid: 'LC-008', name: 'Kavita Nair', age: 25, gender: 'Female', mobile: '9988776608', city: 'Navi Mumbai', referredBy: 'doc-005', registrationDate: today },
  { id: 'pat-009', patientId: 'P-20240009', uhid: 'LC-009', name: 'Arjun Malhotra', age: 38, gender: 'Male', mobile: '9988776609', city: 'Mumbai', referredBy: 'doc-001', registrationDate: today },
  { id: 'pat-010', patientId: 'P-20240010', uhid: 'LC-010', name: 'Sonal Gupta', age: 45, gender: 'Female', mobile: '9988776610', city: 'Pune', referredBy: 'doc-003', registrationDate: today },
];

export const sampleReports: Report[] = [
  {
    id: 'rpt-001', reportNumber: 'RPT-20240001', patientId: 'pat-001', patientName: 'Rahul Kumar', patientAge: 35, patientGender: 'Male',
    doctorId: 'doc-001', doctorName: 'Dr. Rajesh Gupta', status: 'verified',
    items: [
      { testId: 'test-0001', testName: 'Hemoglobin', result: '14.2', unit: 'g/dL', referenceRange: '13.0 - 17.5', flag: 'normal', category: 'Hematology' },
      { testId: 'test-0002', testName: 'Total Leukocyte Count', result: '7500', unit: 'cells/cumm', referenceRange: '4000 - 11000', flag: 'normal', category: 'Hematology' },
      { testId: 'test-0016', testName: 'Platelet Count', result: '2.5', unit: 'lakhs/cumm', referenceRange: '1.5 - 4.0', flag: 'normal', category: 'Hematology' },
    ],
    createdAt: twoDaysAgo, updatedAt: twoDaysAgo, sampleCollectionDate: twoDaysAgo, reportDate: twoDaysAgo, remarks: '',
  },
  {
    id: 'rpt-002', reportNumber: 'RPT-20240002', patientId: 'pat-002', patientName: 'Priya Sharma', patientAge: 28, patientGender: 'Female',
    doctorId: 'doc-002', doctorName: 'Dr. Sunita Patel', status: 'printed',
    items: [
      { testId: 'test-0098', testName: 'TSH', result: '5.8', unit: 'µIU/mL', referenceRange: '0.27 - 4.20', flag: 'high', category: 'Thyroid' },
      { testId: 'test-0096', testName: 'T3', result: '95', unit: 'ng/dL', referenceRange: '80 - 200', flag: 'normal', category: 'Thyroid' },
      { testId: 'test-0097', testName: 'T4', result: '7.2', unit: 'µg/dL', referenceRange: '5.1 - 14.1', flag: 'normal', category: 'Thyroid' },
    ],
    createdAt: twoDaysAgo, updatedAt: yesterday, sampleCollectionDate: twoDaysAgo, reportDate: yesterday, remarks: 'Mildly elevated TSH. Clinical correlation advised.',
  },
  {
    id: 'rpt-003', reportNumber: 'RPT-20240003', patientId: 'pat-003', patientName: 'Vijay Mehta', patientAge: 55, patientGender: 'Male',
    doctorId: 'doc-003', doctorName: 'Dr. Amit Verma', status: 'verified',
    items: [
      { testId: 'test-0082', testName: 'Total Cholesterol', result: '245', unit: 'mg/dL', referenceRange: '< 200', flag: 'high', category: 'Lipid Profile' },
      { testId: 'test-0083', testName: 'Triglycerides', result: '180', unit: 'mg/dL', referenceRange: '< 150', flag: 'high', category: 'Lipid Profile' },
      { testId: 'test-0084', testName: 'HDL Cholesterol', result: '38', unit: 'mg/dL', referenceRange: '> 40', flag: 'low', category: 'Lipid Profile' },
      { testId: 'test-0085', testName: 'LDL Cholesterol', result: '171', unit: 'mg/dL', referenceRange: '< 100', flag: 'high', category: 'Lipid Profile' },
    ],
    createdAt: yesterday, updatedAt: yesterday, sampleCollectionDate: yesterday, reportDate: yesterday, remarks: 'Dyslipidemia noted.',
  },
  {
    id: 'rpt-004', reportNumber: 'RPT-20240004', patientId: 'pat-004', patientName: 'Anjali Desai', patientAge: 42, patientGender: 'Female',
    doctorId: 'doc-001', doctorName: 'Dr. Rajesh Gupta', status: 'pending',
    items: [
      { testId: 'test-0041', testName: 'Total Bilirubin', result: '', unit: 'mg/dL', referenceRange: '0.1 - 1.2', flag: '', category: 'Liver Function' },
      { testId: 'test-0044', testName: 'SGOT / AST', result: '', unit: 'U/L', referenceRange: '0 - 40', flag: '', category: 'Liver Function' },
      { testId: 'test-0045', testName: 'SGPT / ALT', result: '', unit: 'U/L', referenceRange: '0 - 41', flag: '', category: 'Liver Function' },
    ],
    createdAt: yesterday, updatedAt: yesterday, sampleCollectionDate: yesterday, reportDate: today, remarks: '',
  },
  {
    id: 'rpt-005', reportNumber: 'RPT-20240005', patientId: 'pat-005', patientName: 'Suresh Reddy', patientAge: 60, patientGender: 'Male',
    doctorId: 'doc-003', doctorName: 'Dr. Amit Verma', status: 'draft',
    items: [
      { testId: 'test-0069', testName: 'Fasting Blood Sugar', result: '132', unit: 'mg/dL', referenceRange: '70 - 100', flag: 'high', category: 'Diabetes' },
      { testId: 'test-0072', testName: 'HbA1c', result: '7.2', unit: '%', referenceRange: '< 5.7', flag: 'high', category: 'Diabetes' },
    ],
    createdAt: today, updatedAt: today, sampleCollectionDate: today, reportDate: today, remarks: '',
  },
  {
    id: 'rpt-006', reportNumber: 'RPT-20240006', patientId: 'pat-006', patientName: 'Meera Iyer', patientAge: 32, patientGender: 'Female',
    doctorId: 'doc-002', doctorName: 'Dr. Sunita Patel', status: 'pending',
    items: [
      { testId: 'test-0001', testName: 'Hemoglobin', result: '9.8', unit: 'g/dL', referenceRange: '12.0 - 16.0', flag: 'low', category: 'Hematology' },
      { testId: 'test-0105', testName: 'Ferritin', result: '8', unit: 'ng/mL', referenceRange: '15 - 150', flag: 'low', category: 'Iron Profile' },
    ],
    createdAt: today, updatedAt: today, sampleCollectionDate: today, reportDate: today, remarks: '',
  },
];

export const sampleInvoices: Invoice[] = [
  { id: 'inv-001', invoiceNumber: 'INV-20240001', patientId: 'pat-001', patientName: 'Rahul Kumar', reportId: 'rpt-001', items: [{ name: 'CBC', amount: 350 }], totalAmount: 350, discount: 0, paidAmount: 350, dueAmount: 0, paymentMode: 'upi', paymentStatus: 'paid', invoiceDate: twoDaysAgo },
  { id: 'inv-002', invoiceNumber: 'INV-20240002', patientId: 'pat-002', patientName: 'Priya Sharma', reportId: 'rpt-002', items: [{ name: 'Thyroid Profile', amount: 700 }], totalAmount: 700, discount: 50, paidAmount: 650, dueAmount: 0, paymentMode: 'cash', paymentStatus: 'paid', invoiceDate: twoDaysAgo },
  { id: 'inv-003', invoiceNumber: 'INV-20240003', patientId: 'pat-003', patientName: 'Vijay Mehta', reportId: 'rpt-003', items: [{ name: 'Lipid Profile', amount: 450 }], totalAmount: 450, discount: 0, paidAmount: 450, dueAmount: 0, paymentMode: 'card', paymentStatus: 'paid', invoiceDate: yesterday },
  { id: 'inv-004', invoiceNumber: 'INV-20240004', patientId: 'pat-004', patientName: 'Anjali Desai', reportId: 'rpt-004', items: [{ name: 'LFT', amount: 500 }], totalAmount: 500, discount: 0, paidAmount: 200, dueAmount: 300, paymentMode: 'cash', paymentStatus: 'partial', invoiceDate: yesterday },
  { id: 'inv-005', invoiceNumber: 'INV-20240005', patientId: 'pat-005', patientName: 'Suresh Reddy', reportId: 'rpt-005', items: [{ name: 'Diabetic Profile', amount: 550 }], totalAmount: 550, discount: 50, paidAmount: 0, dueAmount: 500, paymentMode: 'cash', paymentStatus: 'unpaid', invoiceDate: today },
  { id: 'inv-006', invoiceNumber: 'INV-20240006', patientId: 'pat-006', patientName: 'Meera Iyer', reportId: 'rpt-006', items: [{ name: 'CBC', amount: 350 }, { name: 'Iron Profile', amount: 800 }], totalAmount: 1150, discount: 100, paidAmount: 1050, dueAmount: 0, paymentMode: 'upi', paymentStatus: 'paid', invoiceDate: today },
];
